import { createFileRoute, Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { useState } from "react";
import {
  QrCode, ScanLine, Sparkles, Shield, Zap, Smartphone, Download,
  Palette, Infinity as InfinityIcon, UserX, ChevronDown, Check, X,
  Link as LinkIcon, Wifi, Contact, MapPin, Calendar, FileText, MessageCircle,
  Youtube, Instagram, Facebook, Twitter, Linkedin, Mail, Phone, Type, MessageSquare,
} from "lucide-react";
import QRGenerator from "@/components/QRGenerator";
import ThemeToggle from "@/components/ThemeToggle";
import Scanner from "@/components/Scanner";
import Footer from "@/components/Footer";

export const Route = createFileRoute("/")({
  component: Home,
  head: () => ({
    meta: [
      { title: "WixelQ — Free QR Code Generator, Beautiful & Unlimited" },
      { name: "description", content: "Create beautiful, high-resolution QR codes for URLs, WiFi, WhatsApp, vCards, PDFs and more. Free forever, no signup, no watermark. Customize colors, gradients, logos and download PNG, JPG, SVG or PDF." },
      { property: "og:title", content: "WixelQ — Free QR Code Generator" },
      { property: "og:description", content: "Beautiful, customizable QR codes in seconds. Free forever." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "/" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "keywords", content: "qr code generator, free qr code generator, qr code maker, create qr code, wifi qr code, whatsapp qr code, instagram qr code, dynamic qr code, qr generator online" },
    ],
    links: [{ rel: "canonical", href: "/" }],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebApplication",
          name: "WixelQ",
          applicationCategory: "UtilityApplication",
          operatingSystem: "Web",
          offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          description: "Free QR code generator with unlimited codes, custom colors, logos and high-resolution downloads.",
        }),
      },
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: FAQS.map((f) => ({
            "@type": "Question",
            name: f.q,
            acceptedAnswer: { "@type": "Answer", text: f.a },
          })),
        }),
      },
    ],
  }),
});

const FAQS = [
  { q: "What is a QR code?", a: "A QR (Quick Response) code is a two-dimensional barcode that stores information like URLs, text, WiFi credentials or contact details, and can be scanned instantly with any smartphone camera." },
  { q: "Is WixelQ really free?", a: "Yes. Every QR code you generate is 100% free, unlimited, and downloads carry no watermark or attribution." },
  { q: "Can I generate unlimited QR codes?", a: "Absolutely — no daily limits, no account required, no hidden fees." },
  { q: "How do I create a QR code for my website?", a: "Choose the Website category, paste your URL, customize the design if you like, and click Download. It takes under 10 seconds." },
  { q: "Can I download PNG, JPG, SVG or PDF?", a: "Yes. WixelQ supports high-resolution PNG and JPG, scalable SVG for print, and a printable PDF view." },
  { q: "Are QR codes permanent?", a: "Static QR codes (which is what WixelQ generates) never expire and always point to the same content." },
  { q: "Can I customize QR colors and add a logo?", a: "Yes — choose solid or gradient colors, dot & eye styles, rounded corners, and upload your own logo for the center." },
  { q: "Do QR codes expire?", a: "The QR codes generated by WixelQ are static and never expire. The destination (e.g. a URL) only becomes unreachable if you take it down." },
];

const FEATURES = [
  { icon: InfinityIcon, title: "Free Forever", desc: "Unlimited QR codes, always $0." },
  { icon: UserX, title: "No Signup", desc: "Start creating instantly, no account." },
  { icon: Palette, title: "Custom Design", desc: "Colors, gradients, logos, dot styles." },
  { icon: Download, title: "HD Downloads", desc: "PNG, JPG, SVG and print-ready PDF." },
  { icon: Shield, title: "Private & Secure", desc: "Everything runs in your browser." },
  { icon: Smartphone, title: "Mobile Friendly", desc: "Design on desktop, phone or tablet." },
  { icon: Zap, title: "Instant Preview", desc: "Live preview while you edit." },
  { icon: Sparkles, title: "Premium Feel", desc: "Beautiful codes that fit your brand." },
];

const CATS = [
  { icon: LinkIcon, label: "Website" }, { icon: Type, label: "Text" }, { icon: Mail, label: "Email" },
  { icon: Phone, label: "Phone" }, { icon: MessageSquare, label: "SMS" }, { icon: MessageCircle, label: "WhatsApp" },
  { icon: Wifi, label: "WiFi" }, { icon: Contact, label: "vCard" }, { icon: MapPin, label: "Location" },
  { icon: Calendar, label: "Event" }, { icon: FileText, label: "PDF" }, { icon: Youtube, label: "YouTube" },
  { icon: Instagram, label: "Instagram" }, { icon: Facebook, label: "Facebook" }, { icon: Twitter, label: "X" },
  { icon: Linkedin, label: "LinkedIn" },
];

function Home() {
  const [scannerOpen, setScannerOpen] = useState(false);

  return (
    <div className="relative min-h-screen overflow-x-hidden">
      {/* Floating background shapes */}
      <div aria-hidden className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
        <div className="animate-float-slow absolute -top-32 -left-32 h-96 w-96 rounded-full bg-gradient-brand opacity-20 blur-3xl" />
        <div className="animate-float-slower absolute top-1/3 -right-40 h-[28rem] w-[28rem] rounded-full opacity-20 blur-3xl" style={{ background: "linear-gradient(135deg, oklch(0.75 0.14 220), oklch(0.65 0.18 295))" }} />
        <div className="animate-float-slow absolute bottom-0 left-1/3 h-80 w-80 rounded-full bg-gradient-brand opacity-15 blur-3xl" />
      </div>

      {/* Nav */}
      <header className="sticky top-0 z-40 backdrop-blur-xl bg-background/60 border-b border-border/60">
        <nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3">
          <a href="#" className="flex items-center gap-2 font-semibold">
            <span className="inline-flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-brand text-white ring-glow">
              <QrCode className="h-4 w-4" />
            </span>
            <span className="text-lg tracking-tight">WixelQ</span>
          </a>
          <div className="hidden md:flex items-center gap-8 text-sm text-muted-foreground">
            <a href="#generator" className="hover:text-foreground transition">Generator</a>
            <Link to="/features" className="hover:text-foreground transition">Features</Link>
            <Link to="/about" className="hover:text-foreground transition">About</Link>
            <Link to="/blog" className="hover:text-foreground transition">Blog</Link>
            <Link to="/contact" className="hover:text-foreground transition">Contact</Link>
          </div>
          <div className="flex items-center gap-2">
            <ThemeToggle />
            <button onClick={() => setScannerOpen(true)} className="hidden sm:inline-flex items-center gap-1.5 rounded-full border border-border bg-card/60 px-3 py-1.5 text-sm hover:border-primary/40">
              <ScanLine className="h-4 w-4" /> Scan
            </button>
            <a href="#generator" className="inline-flex items-center gap-1.5 rounded-full bg-gradient-brand px-4 py-2 text-sm font-medium text-white ring-glow hover:brightness-110 transition">
              Generate
            </a>
          </div>
        </nav>
      </header>

      {/* Hero */}
      <section className="relative mx-auto max-w-7xl px-4 pt-16 pb-8 md:pt-28 md:pb-16 text-center">
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
          <div className="inline-flex items-center gap-2 rounded-full border border-border bg-card/60 px-3 py-1 text-xs text-muted-foreground backdrop-blur">
            <Sparkles className="h-3 w-3 text-primary" /> The premium free QR code generator
          </div>
          <h1 className="mx-auto mt-6 max-w-4xl text-5xl md:text-7xl font-semibold tracking-tight leading-[1.05]">
            Create <span className="text-gradient">beautiful QR codes</span><br className="hidden md:block" /> in seconds.
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground">
            Generate professional QR codes for websites, WiFi, social media, business cards, PDFs and more.
            Fully customizable. High-resolution downloads. Completely free.
          </p>
          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <a href="#generator" className="inline-flex items-center gap-2 rounded-full bg-gradient-brand px-6 py-3 text-sm font-medium text-white ring-glow hover:brightness-110 transition">
              <QrCode className="h-4 w-4" /> Generate QR Code
            </a>
            <button onClick={() => setScannerOpen(true)} className="inline-flex items-center gap-2 rounded-full border border-border bg-card/60 px-6 py-3 text-sm font-medium hover:border-primary/40 transition">
              <ScanLine className="h-4 w-4" /> Scan QR Code
            </button>
          </div>
          <p className="mt-4 text-xs text-muted-foreground">No signup · No watermark · Unlimited</p>
        </motion.div>

        {/* Animated mockup */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.2 }} className="relative mx-auto mt-14 max-w-3xl">
          <div className="glass rounded-3xl p-8">
            <div className="grid gap-6 md:grid-cols-[1fr_auto]">
              <div className="text-left space-y-3">
                <div className="text-xs uppercase tracking-wider text-muted-foreground">Live preview</div>
                <div className="text-2xl font-semibold">wixelq.com</div>
                <div className="flex gap-2">
                  <span className="rounded-full bg-secondary px-2.5 py-1 text-xs">Gradient</span>
                  <span className="rounded-full bg-secondary px-2.5 py-1 text-xs">Rounded</span>
                  <span className="rounded-full bg-secondary px-2.5 py-1 text-xs">HD PNG</span>
                </div>
                <div className="pt-4 space-y-2">
                  <ProgressLine label="Design" value={100} />
                  <ProgressLine label="Export" value={90} />
                  <ProgressLine label="Free" value={100} />
                </div>
              </div>
              <motion.div animate={{ rotate: [0, -1.5, 1.5, 0] }} transition={{ duration: 8, repeat: Infinity }} className="mx-auto h-40 w-40 rounded-2xl bg-gradient-brand p-3 ring-glow">
                <div className="grid h-full w-full grid-cols-8 grid-rows-8 gap-0.5 rounded-lg bg-white p-2">
                  {Array.from({ length: 64 }).map((_, i) => {
                    const on = [0,1,2,5,6,7,8,10,13,15,16,18,20,23,24,25,26,29,30,33,35,36,40,41,43,45,48,50,52,55,56,57,58,61,62,63].includes(i);
                    return <div key={i} className={on ? "bg-slate-900 rounded-[2px]" : ""} />;
                  })}
                </div>
              </motion.div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Generator */}
      <QRGenerator />

      {/* Categories */}
      <section id="categories" className="mx-auto max-w-7xl px-4 py-16">
        <SectionHeading eyebrow="20+ Categories" title="One QR generator for everything" />
        <div className="mt-10 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-8 gap-3">
          {CATS.map(({ icon: Icon, label }) => (
            <motion.div key={label} whileHover={{ y: -4 }} className="glass flex flex-col items-center gap-2 rounded-2xl p-4 text-center">
              <span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-brand/10 text-primary">
                <Icon className="h-5 w-5" />
              </span>
              <span className="text-xs font-medium">{label}</span>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section id="features" className="mx-auto max-w-7xl px-4 py-16">
        <SectionHeading eyebrow="Why WixelQ" title="Everything you need. Nothing you don't." />
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {FEATURES.map(({ icon: Icon, title, desc }) => (
            <motion.div key={title} whileHover={{ y: -4 }} className="glass rounded-2xl p-6">
              <span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-brand text-white ring-glow">
                <Icon className="h-5 w-5" />
              </span>
              <h3 className="mt-4 font-semibold">{title}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="mx-auto max-w-7xl px-4 py-16">
        <SectionHeading eyebrow="How it works" title="Four steps. Under a minute." />
        <div className="mt-10 grid gap-4 md:grid-cols-4">
          {[
            { n: "01", t: "Select type", d: "Website, WiFi, vCard, and more." },
            { n: "02", t: "Enter info", d: "Fill in the fields on the left." },
            { n: "03", t: "Customize", d: "Colors, logo, styles, gradients." },
            { n: "04", t: "Download", d: "PNG, JPG, SVG or PDF — free." },
          ].map((s) => (
            <div key={s.n} className="glass rounded-2xl p-6">
              <div className="text-gradient font-display text-3xl font-semibold">{s.n}</div>
              <h3 className="mt-2 font-semibold">{s.t}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{s.d}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Compare */}
      <section id="compare" className="mx-auto max-w-5xl px-4 py-16">
        <SectionHeading eyebrow="Compare" title="Why choose WixelQ" />
        <div className="mt-10 glass overflow-hidden rounded-2xl">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border/60 text-left">
                <th className="p-4 font-medium text-muted-foreground">Feature</th>
                <th className="p-4 font-semibold">WixelQ</th>
                <th className="p-4 font-medium text-muted-foreground">Others</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["Unlimited free QR codes", true, false],
                ["No signup required", true, false],
                ["No watermark", true, false],
                ["Custom logos & gradients", true, true],
                ["SVG & PDF export", true, false],
                ["Local history & privacy", true, false],
              ].map(([f, a, b], i) => (
                <tr key={i} className="border-b border-border/40 last:border-0">
                  <td className="p-4">{f as string}</td>
                  <td className="p-4">{a ? <Check className="h-4 w-4 text-primary" /> : <X className="h-4 w-4 text-muted-foreground" />}</td>
                  <td className="p-4">{b ? <Check className="h-4 w-4 text-muted-foreground" /> : <X className="h-4 w-4 text-muted-foreground" />}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="mx-auto max-w-3xl px-4 py-16">
        <SectionHeading eyebrow="FAQ" title="Questions, answered" />
        <div className="mt-10 space-y-3">
          {FAQS.map((f, i) => <FAQItem key={i} q={f.q} a={f.a} />)}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-5xl px-4 py-20">
        <div className="glass relative overflow-hidden rounded-3xl p-10 md:p-16 text-center">
          <div aria-hidden className="absolute inset-0 -z-10 opacity-30 bg-gradient-brand blur-3xl" />
          <h2 className="text-4xl md:text-5xl font-semibold tracking-tight">Your next QR code is one click away.</h2>
          <p className="mt-4 text-muted-foreground">Free forever. No signup. No watermark.</p>
          <a href="#generator" className="mt-8 inline-flex items-center gap-2 rounded-full bg-gradient-brand px-6 py-3 text-sm font-medium text-white ring-glow hover:brightness-110 transition">
            <QrCode className="h-4 w-4" /> Generate now
          </a>
        </div>
      </section>

      <Footer />

      <Scanner open={scannerOpen} onClose={() => setScannerOpen(false)} />
    </div>
  );
}

function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) {
  return (
    <motion.div initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} className="text-center">
      <div className="text-xs uppercase tracking-[0.2em] text-primary/80">{eyebrow}</div>
      <h2 className="mt-3 text-3xl md:text-5xl font-semibold tracking-tight">{title}</h2>
    </motion.div>
  );
}

function ProgressLine({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <div className="mb-1 flex justify-between text-xs text-muted-foreground"><span>{label}</span><span>{value}%</span></div>
      <div className="h-1.5 overflow-hidden rounded-full bg-secondary">
        <motion.div initial={{ width: 0 }} animate={{ width: `${value}%` }} transition={{ duration: 1.4, ease: "easeOut" }} className="h-full bg-gradient-brand" />
      </div>
    </div>
  );
}

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="glass rounded-2xl">
      <button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between gap-4 p-5 text-left">
        <span className="font-medium">{q}</span>
        <ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      <motion.div initial={false} animate={{ height: open ? "auto" : 0, opacity: open ? 1 : 0 }} className="overflow-hidden">
        <p className="px-5 pb-5 text-sm text-muted-foreground">{a}</p>
      </motion.div>
    </div>
  );
}

